spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org.springframework.cache: TRACE
